### ISSUE TITLE
Add tests to current KATAS

### ISSUE THREAD

**Issue by johnslay** [luismartinezs/react-katas#1]
Nice project by the way! I noticed the reddit comment about writing tests and I have got you started with an example here https://github.com/johnslay/react-katas/tree/test-example

**Comment by luismartinezs** [comment]
Thanks! Adding tests is something I'll definitely do soon

**Comment by luismartinezs** [comment]
This project is not severely outdated, and I created it when I was just starting as a dev. At this point it would make more sense to redo this from scratch.
